"""The same rules under another harness: its agent's name, user file, tools and built-ins."""

from agentltl_coding import Guard, Harness, Paths, configure, current, lint, loads

from .conftest import CLAUDE, COPILOT, run


def with_harness(harness, fn):
    configure(harness)
    try:
        return fn()
    finally:
        configure(CLAUDE)


def test_messages_name_the_harness_agent_and_shell_tool():
    codex = Harness(name="codex", agent="Codex", user_dir="~/.codex",
                    shell_tools={"shell": "cmd"})

    def run():
        g = Guard(loads("rules: [{id: no-push, never: git_push, mode: ask}]"), Paths("/p", "/p"))
        g.restore({})
        return g.decide("shell", {"cmd": "git push"})

    v = with_harness(codex, run)
    assert v.action == "ask" and "Codex cannot override this rule" in v.reason


def test_builtins_come_from_the_harness_and_settings_switch_them_off():
    rule = {"id": "no-sudo", "never": "sudo", "why": "x"}
    h = Harness(builtins={"no_sudo": rule})

    assert with_harness(h, lambda: [r.id for r in _load("")]) == ["no-sudo"]
    assert with_harness(h, lambda: [r.id for r in _load("settings: {no_sudo: false}")]) == []
    assert current() is CLAUDE


def _load(text):
    import os
    import tempfile
    path = os.path.join(tempfile.mkdtemp(), "AGENTLTL.yaml")
    with open(path, "w") as fh:
        fh.write(text or "rules: []")
    from agentltl_coding import load
    return load([path]).rules


def test_lint_catches_a_misspelt_tool_in_a_formula():
    rs = loads("rules: [{id: r, ltl: 'G(now(\"git_psuh\") -> X(G(!now(\"git_psuh\"))))'}]")
    assert any("git_psuh" in w and "git_push" in w for w in lint(rs))
    rs = loads("rules: [{id: r, ltl: 'G(now(\"git_push\") -> X(G(!now(\"git_push\"))))'}]")
    assert lint(rs) == []


# ── GitHub Copilot CLI: its own tool names, the library's rules ─────────────────

def _copilot(fn):
    return with_harness(COPILOT, fn)


def _guard(text, cwd):
    g = Guard(loads(text, Paths(cwd, cwd)), Paths(cwd, cwd))
    g.restore({})
    return g


def test_copilot_tools_are_checked_under_the_canonical_names(tmp_path):
    (tmp_path / "a.txt").write_text("x")

    def go():
        g = _guard("use: [read-before-overwrite]", str(tmp_path))
        create = ("create", {"path": "a.txt", "file_text": "y"})
        return run(g, create, ("view", {"path": "a.txt"}), create,
                   ("create", {"path": "new.txt", "file_text": "y"}))

    assert _copilot(go) == ["deny", "none", "none", "none"]


def test_copilot_bash_is_a_shell_tool_and_the_trace_keeps_canonical_names():
    def go():
        g = _guard("rules: [{id: t, before: [pytest, git_push]}]", "/p")
        out = run(g, ("bash", {"command": "git push", "description": "push"}),
                  ("bash", {"command": "pytest -q"}), ("bash", {"command": "git push"}))
        return out, [c["tool_name"] for c in g.trace]

    assert _copilot(go) == (["deny", "none", "none"], ["pytest", "git_push"])


def test_an_edit_matches_rules_on_edit_by_file_path():
    def go():
        g = _guard("rules: [{id: no-env, never: {tool: Edit, where: {file_path: '*.env'}}}]", "/p")
        return run(g, ("edit", {"path": "/p/.env", "old_str": "a", "new_str": "b"}),
                   ("edit", {"path": "/p/a.py", "old_str": "a", "new_str": "b"}))

    assert _copilot(go) == ["deny", "none"]


def test_library_entries_for_another_agent_switch_nothing_on():
    text = "use: [no-claude-coauthor, no-copilot-coauthor, subagents-on-sonnet]"
    claude = [r.id for r in loads(text).rules]
    copilot = _copilot(lambda: [r.id for r in loads(text).rules])
    assert claude == ["no-claude-coauthor", "subagents-on-sonnet", "subagents-on-sonnet-no-fork"]
    assert copilot == ["no-copilot-coauthor"]


def test_no_copilot_coauthor():
    def go():
        g = _guard("use: [no-copilot-coauthor]", "/p")
        return run(g, 'git commit -m x -m "Co-authored-by: Copilot <223556219+Copilot@users.'
                      'noreply.github.com>"', 'git commit -m "fix bug"')

    assert _copilot(go) == ["deny", "none"]


def test_no_vibe_coauthor():
    vibe = Harness(name="mistral-vibe", agent="Vibe", user_dir="~/.vibe")

    def go():
        g = _guard("use: [no-vibe-coauthor, no-copilot-coauthor]", "/p")
        return [r.id for r in g.ruleset.rules], run(
            g, 'git commit -m x -m "Generated by Mistral Vibe." '
               '-m "Co-Authored-By: Mistral Vibe <vibe@mistral.ai>"', 'git commit -m "fix bug"')

    assert with_harness(vibe, go) == (["no-vibe-coauthor"], ["deny", "none"])
    assert [r.id for r in loads("use: [no-vibe-coauthor]").rules] == []


def test_no_codex_coauthor():
    codex = Harness(name="codex", agent="Codex", user_dir="~/.codex")

    def go():
        g = _guard("use: [no-codex-coauthor, no-vibe-coauthor]", "/p")
        return [r.id for r in g.ruleset.rules], run(
            g, "git commit -m x -m 'Co-authored-by: Codex <noreply@openai.com>'",
            'git commit -m x -m "Generated with [Codex](https://openai.com/codex/)."',
            'git commit -m "fix bug"')

    assert with_harness(codex, go) == (["no-codex-coauthor"], ["deny", "deny", "none"])
    assert [r.id for r in loads("use: [no-codex-coauthor]").rules] == []


def test_auto_modes_and_project_env_come_from_the_harness(monkeypatch, tmp_path):
    from agentltl_coding.cli import _here
    from agentltl_coding.guard import is_auto
    assert is_auto("bypassPermissions") and not _copilot(lambda: is_auto("bypassPermissions"))
    monkeypatch.setenv("CLAUDE_PROJECT_DIR", str(tmp_path))
    assert _here()[1] == str(tmp_path)
    assert _copilot(lambda: _here()[1]) != str(tmp_path)
